version: "3"
services:
  db:
    container_name: nestjs-api-db
    image: mysql:8.0.30-debian
    ports: 
      - 3307:3306
    env_file:
      - ./.env
    volumes:
      - .docker/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 60s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12.12-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    env_file:
      - ./.env
