version: "3"
services:
  db:
    container_name: nestjs-api-db
    image: mysql:8.0.30-debian
    ports: 
      - 3307:3306
    env_file:
      - ./.env
    volumes:
      - .docker/mysql:/var/lib/mysql
    networks:
      - nest-api-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 60s
      retries: 5

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: always
    ports: 
      - "8081:8080"
    networks:
      - nest-api-network
    depends_on:
      db:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3.12.12-management
    ports:
      - 15672:15672
      - 5672:5672
    env_file:
      - ./.env
    networks:
      - nest-api-network
  
networks:
  nest-api-network:
    driver: bridge